### ISSUE TITLE
GCC options `-march=native` and `-mtune=native` not used

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1042]
Why aren't they used? Most often one will get more performance by using these options, but perhaps it is a maintenance issue?

**Comment by wbhart** [comment]
It makes generating binaries harder as it relies on the target machine being the same as the machine on which the code was built.

I'm not sure what the default is as far as other libraries are concerned. But unless you have a configure option to distinguish host and build machine (which we don't) I would guess the default is to not use these.

**Comment by albinahlback** [comment]
I noticed it when I compared GMP's makefile, since they have it.

I was thinking that one have a configure option like `-no-specific-architecture` when configuring FLINT so that it just works 'out of the box' when configuring binaries for packages like FLINT_JLL.

**Comment by wbhart** [comment]
Well GMP has --build and --host, so that is not comparable. That's the other way of doing it. Inventing one's own configure switched for things that are not germane to one's library is frowned upon.

**Comment by fingolfin** [comment]
The problem with `-march=native` is that it's a footgun, and can easily lead to weird crashes, esp. for downstream packagers. Power users who want every last percent of performance will know how to manually add it to the compiler flags.

**Comment by albinahlback** [comment]
Do you suggest using `-march=myspecificprocessor` instead or simply removing this flag by default? I mainly want to do this as GMP sets this flag by default, which I think is a good idea.

**Comment by fingolfin** [comment]
I personally would just not bother with these, and instead include somewhere in the build instructions a hint like this (of course adjusted to make sure it actually works; I tested nothing):
> In order to maximize performance, you can compile FLINT specifically for your computer.
> The resulting binary will be faster, but also won't work in general on other computers
> (so this is usually a bad idea if you plan to install it for use by multiple computers
> in a lab, or are preparing binaries for distribution).
>
> To achieve this, add `-march=native` to the `CFLAGS` environment variable before
> compiling FLINT.

In the same place, one could also mention `-O3` (which despite its bad rep seems to work great for contemporary compilers).

**Comment by albinahlback** [comment]
This shouldn't be a default setting.
