### ISSUE TITLE
Improve compile time

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1070]
What can be done regarding the compile time for FLINT?

**Comment by albinahlback** [comment]
If a file `XXX.c` requires `flint.h`, where `gmpcompat.h` is enlisted as an inclusion, would that require a "compilation" of `gmpcompat.h`? Follow-up question: if one compiles FLINT, would such a compilation be necessary for every file being compiled?

**Comment by wbhart** [comment]
Headers are generally only included once. 

If the compile time is too slow for you, you can just build a shared or static library and not both. That will halve the time.

I don't think much more can be done about it. We already use dependency tracking to speed it up.

**Comment by tthsqe12** [comment]
In order to improve compile time:
1. Have 8 real cores and make -j8
2. Have an SSD
3. disable -g in the makefile (with -g, the whole source code is essentially included in the binary)
4. ./configure --disable-static

**Comment by fredrik-johansson** [comment]
Well, bloated header files are an issue. Just now I tried to compiling generic-rings and adding "#include flint/fmpz_mpoly.h" to gr.h increases the time from 18 to 25 seconds, for example.

We should consider ways to restructure header files so that you don't need to include thousands of lines of function prototypes and inline code when you only need a single typedef.

**Comment by tthsqe12** [comment]
Sure. There should be an fmpz_poly.h for the official stuff and fmpz_poly-impl.h for the internal stuff.

**Comment by albinahlback** [comment]
I'd like to make every header as independent of each other as possible in order to improve compilation time. Moreover, end users using `XXX_mat` does not necessarily need to have any `XXX`-functions.

However, there are some problems with this. For example, `fmpz_mat.h` require `fmpz_equal` and `fmpz_swap` for inlining, and so one at the current state one must include `fmpz.h` in `fmpz_mat.h`. It's quite reasonable to de-inline these functions, at least those with `fmpz_equal`, and a local version of `fmpz_swap` could easily be defined.

What do you think of this?

**Comment by albinahlback** [comment]
I'm planning to not use `Makefile.subdirs` to building FLINT. Will probably keep it for everything else. This should strip away a couple of seconds from the compilation process, but also allow for better multithreading in Make.

To see just how long it actually takes to call `Makefile.subdirs`, call `time make clean`. On my laptop, it amounts to about 3 seconds. This should allow the rebuilding FLINT to be substantially faster when building a shared library.

**Comment by albinahlback** [comment]
I will also remove the inclusion of MPFR for most files, as FLINT is almost independent of MPFR. This will remove about 1000 lines to be included into every file.

**Comment by albinahlback** [comment]
Due to the build of `fq`-things being slow, I would like to draw the conclusion that the template headers might be slowing things down by a considerate amount. For example, every time a file in `fq_default_poly_factor` has to be compiled, it needs to do the templates for `fq[_nmod, _zech]_poly`, which in turn needs to do the templates for `fq[_nmod, _zech]`.

But perhaps this will be fixed as I reduce the amount of inclusions.

**Comment by wbhart** [comment]
I hope you are an expert at make! The current makefiles took years to get right, with many, many people contributing fixes for various toolchains. I don't personally see how you can get rid of Makefile.subdirs and keep all of the current features of the build system. But have at it if you believe your makefu is up to it.

**Comment by albinahlback** [comment]
As I've closed one PR regarding this, I am wondering if and how we can proceed with this issue.

I think of three possible scenarios:

1. We can try to merge `.c`-files as many directories are in some regards bloated. Take `fmpz_equal[_ui/_si]` for example: Do we really need three different files for equalities? I think merging everything to one single file is a bit excessive, but I think that one can split it up into a bunch of categories such as
    - Memory management (init, clear, etc)
    - Arithmetics (add, mul, addmul, etc)
    - Getters and setters (get_ui, set_si, whatever)
    - Any applicable category, such as number theoretic functions for `fmpz`, which could include `fmpz_lcm`, `fmpz_gcd`, `fmpz_xgcd`.

    This would result in the least amount of work, be easy to review and would result in the best possible speedup (reference to Max's comment: https://github.com/wbhart/flint2/pull/1102#issuecomment-1123684713).

2. We can try to minimize the bloating of header files. However, as I think I demonstrated quite well, this takes *a lot* of effort, both from the people behind the PR and from the reviewers. You basically have to change the whole repository if you want to make changes that can be noticed. Sure, you can do it in smaller steps, but you never get around the fact that almost every file has to be changed in order to manage the changed header files and that many source files includes too much.

3. We come to an agreement that none of these options are feasible, hence closing this issue.

**Comment by fredrik-johansson** [comment]
I'd be open to putting type variants of the same function in the same file in trivial cases, e.g. fmpz_equal, fmpz_equal_si, fmpz_equal_ui can all go in fmpz/equal.c. Other than that, I'd prefer to keep the separate .c files as far as possible.

I think I'd prefer to conservatively grind down the header files a bit. Maybe start with just a single module (one of the more slowly-compiling) and see what can be done about redundant includes.

Something that immediately comes to mind is that flint.h shouldn't include mpfr.h. MPFR functions are only used in a handful of modules and files which can include mpfr.h explicitly. Well, we do need the mpfr_t typedef in fmpz_get_mpfr in fmpz.h and fmpq_get_mpfr in fmpq.h. I suppose there we could define those function prototypes only if mpfr.h is included by the user before fmpz.h/fmpq.h? (I don't advocate that approach for flint-internal types, but it wouldn't be unreasonable here.)

**Comment by albinahlback** [comment]
> I'd be open to putting type variants of the same function in the same file in trivial cases, e.g. fmpz_equal, fmpz_equal_si, fmpz_equal_ui can all go in fmpz/equal.c. Other than that, I'd prefer to keep the separate .c files as far as possible.

Sounds good, I'm all for this.

> I think I'd prefer to conservatively grind down the header files a bit, even if it's a lot of manual work. Maybe start with just a single module (one of the more slowly-compiling) and see what can be done about redundant includes, unnecessary inlines etc.
> 
> Something that immediately comes to mind is that flint.h shouldn't include mpfr.h. MPFR functions are only used in a handful of modules and files which can include mpfr.h explicitly. Well, we do need the mpfr_t typedef in fmpz_get_mpfr in fmpz.h and fmpq_get_mpfr in fmpq.h. I suppose there we could define those function prototypes only if mpfr.h is included by the user before fmpz.h/fmpq.h? (I don't advocate that approach for flint-internal types, but it wouldn't be unreasonable here.)

Yeah, this is probably the easiest to achieve. You can simply strip `#include "mpfr.h"` from every header except `mpfr_vec` etc, and simply do stuff like
```c
#ifdef __MPFR_H
void fmpz_set_mpfr(blabla);
#endif
```
then instruct users that if they want to use MPFR types, they have to include MPFR.
