### ISSUE TITLE
make -jn check MOD=foo not working

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint2#1125]
This fails to run in parallel:

    fredrik@mordor:~/src/flint2$ make -j8 check MOD=fmpz
    make[1]: Entering directory '/home/fredrik/src/flint2'
    make[1]: Nothing to be done for 'shared'.
    make[1]: Leaving directory '/home/fredrik/src/flint2'
    make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.

But this works in Arb where the relevant lines in Makefile.in (based on an old version of the Flint) read:

	$(AT)$(foreach dir, $(MOD), test ! -d $(dir) || mkdir -p build/$(dir)/test; BUILD_DIR=../build/$(dir); export BUILD_DIR; test ! -d $(dir) || $(MAKE) -f ../Makefile.subdirs -C $(dir) check || exit $$?;)
	$(AT)$(foreach ext, $(EXTENSIONS), $(AT)$(foreach dir, $(MOD), MOD_DIR=$(dir); export MOD_DIR; test ! -d $(ext)/$(dir) || mkdir -p build/$(dir)/test; BUILD_DIR=$(CURDIR)/build/$(dir); export BUILD_DIR; test ! -d $(ext)/$(dir) || $(MAKE) -f $(CURDIR)/Makefile.subdirs -C $(ext)/$(dir) check || exit $$?;))

In Flint these lines have been replaced by:

	$(AT)$(foreach mod, $(MOD), $(call test_mod,$(mod)) || exit $$?;)
	$(AT)$(foreach ext, $(EXTENSIONS), $(foreach mod, $(MOD), $(call test_mod_ext,$(mod),$(ext)) || exit $$?;))

I don't see an obvious place to put the '+' suggested by the warning message...

**Comment by albinahlback** [comment]
I've also had problems with this. I believe it works if you run just `-j` instead of `-j8`.

**Comment by albinahlback** [comment]
But of course, then you cannot specify the number of threads.

**Comment by albinahlback** [comment]
I suppose this is fixed. Reopen if this is still present.
