### ISSUE TITLE
Force the flag `-D _WIN64` on Cygwin

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1131]
If one supplies their own C-flags on Cygwin when compiling FLINT, one will get warnings/errors if one does not specify `-D _WIN64`.

**Comment by wbhart** [comment]
Perhaps you can write to Microsoft and tell them:

https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170

**Comment by albinahlback** [comment]
This is not a good idea.
