### ISSUE TITLE
Proposition for drastically reducing build time

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1146]
As you might know, I've recently tried to make a large effort in reducing the building time in FLINT without any real success.

In this issue I will give my thoughts on the available solutions to reduce building time, then propose an idea of how to solve this problem.

### Thoughts about how to reduce build time

There are basically three ways that reduces building time:

1. Set compiler flags such that the compiler builds faster. 
2. Reduce the amount of source code.
3. Reduce the amount of header code included in source files.
4. Concatenate source files.

(1) is a no-go. Cleaning up FLINT would result in (2), but this would only get you a very minor building speed increase.

Although (3) seems like a good idea in general as it also has a positive effect for other libraries using FLINT headers, it really boils down to rewriting every single file; No one will merge such a PR.

Regarding (4), Max showed in [this post](https://github.com/wbhart/flint2/pull/1102#issuecomment-1123684713) that concatenating source files drastically reduces build time. I suspect that this would be the easiest solution with the best effect. However, as Bill is opposed to this idea, I will refrain to do this.

### Idea

So we would basically like to compile concatenate files without developing in concatenated files. My idea is the following, where I assume that the building directory is `fmpz`:

1. Introduce implementation headers, such as `fmpz-impl.h`, only consisting of the inclusions that every source file in `fmpz/` need.
2. Every source file under `fmpz/` only includes `fmpz-impl.h`.
3. Modify the building process to the following:
    a. Concatenate `fmpz/*.c` to one file, say `build/fmpz_concat.c`. For this large directory, it merely takes about 0.02 seconds on my system.
    b. Compile `build/fmpz_concat.c` to an object file. Max showed that building such a file takes only 2% of the time compared to compiling every individual source file.
4. Build library from these object files.

With these estimates, it should take about 10 seconds to compile a shared FLINT library from scratch *single-threaded*.

Please let me know if you'd like me to explain why (1) is necessary.

#### The good

- CMake still works as it should. As I won't change `CMakeLists.txt`, it is important that it still works without any fixups. As every source file will still include every header needed, CMake will still work without any problems.
- Blazing fast building time from scratch, i.e. very newbie friendly!
- Blazing fast when only changing one header.
- Very fast even when only one source file is changed.
- The source/header/directory system will not be drastically changed.

#### The bad

- One needs to change a lot of files. However, using `sed` should drastically reduce the time spend on this.
- Building via CMake will probably take a little longer to build as every source file will include more than needed. However, if the same idea is realized for this building system, then of course the timings here will be reduced as well.

### Your thoughts on this

What do you think? Would you accept such a PR?

Ping @wbhart @fredrik-johansson @tthsqe12

**Comment by isuruf** [comment]
Btw, doing this with cmake is just a couple of lines of code.

wget https://raw.githubusercontent.com/sakra/cotire/master/CMake/cotire.cmake -O CMake/cotire.cmake
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9784633c4..39f9ef717 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -13,6 +13,8 @@ project(flint LANGUAGES C CXX)
 
 list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/CMake")
 
+include(cotire)
+
 if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Choose the type of build" FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
@@ -298,6 +300,8 @@ if(NOT MSVC)
        target_link_libraries(flint PUBLIC m)
 endif()
 
+cotire(flint)
+
 include(GNUInstallDirs)
 
 install(TARGETS flint
 ```

**Comment by albinahlback** [comment]
By the way, what is the purpose of extensions in Makefile?

Would it be okay if I remove everything in the Makefile that has to do with C++? Would it be okay if I remove everything in the Makefile related to NTL? If not, do we intend to keep them in FLINT? If so, why? They are not tested in the CI.

**Comment by wbhart** [comment]
Flint has the ability to build additional modules that are defined in an external package. For example, Arb and Antic used to be Flint extension modules. In the end these packages became too important and the distributions wanted to include them, so they asked us to add separate Makefiles for those projects, instead of using the Flint extension module capability.

The C++ wrapper and NTL interface are still both widely used (including by Sage, one of our most important "customers"). The C++ parts can only be removed if they are put into a separate package. But it is up to @fredrik-johansson whether he wants to do this or not. It obviously won't happen in the current release.

I believe there are test files for the C++ interface but it takes ages to compile them, so we disconnected the tests I think. I don't know that we ever had tests for the NTL interface as that would require making NTL a dependency of Flint or more Makefile massaging which we never got around to. Of course other projects test the NTL interface and regularly report issues if they occur, which we fix for each release.

**Comment by albinahlback** [comment]
Thanks for your input, Bill! Then I will not remove any functionality!

**Comment by albinahlback** [comment]
I will split this up into the following PR's:

1. Create `-impl.h` headers, which all the source files uses.
2. Change Makefile.

**Comment by albinahlback** [comment]
Okay, I'm almost done with 1. Seems like it will take about 30 seconds on a 4700k single-threaded, i.e. about 90-95% less time for building. But still a great improvement in compilation time!
