### ISSUE TITLE
Change check for `COEFF_IS_MPZ`

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1154]
Currently is defined something like
```c
#define COEFF_IS_MPZ(x) ((((ulong) x) >> 62) == UWORD(1))
```

If we change it to
```c
#define COEFF_IS_MPZ(x) (((slong) x) >= (WORD(1) << 62))
```
it should be one instruction less, I think. Moreover, I think that this would open up to using SIMD instructions for `fmpz_vec`.

**Comment by wbhart** [comment]
SIMD relies on having vectors all of whose elements have the same fixed size. I very much doubt you can effectively use SIMD for `fmpz_vec`.

**Comment by fredrik-johansson** [comment]
The proposed version is not correct (consider negative values).

Anyway, SIMD is not going to be useful when you have to branch for MPZ pointers. The fmpz functions where SIMD can be useful are primarily the ones with higher than O(n) complexity, like basecase polynomial/matrix multiplication, where you can check the bit sizes with an initial pass over the data.

Then the problem remains that the SIMD instructions don't do 64-bit integer math very well.

**Comment by fredrik-johansson** [comment]
No, you're not wrong. My mistake. Have you checked that the compiler doesn't already emit the same code for these two versions though?

**Comment by albinahlback** [comment]
Yeah, I can check!
