### ISSUE TITLE
Function to return number of available threads/workers

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint2#1160]
Would it make sense to add something like this? @tthsqe12

```
slong thread_pool_num_available(thread_pool_t T)
{
    slong i, num = 0;
    thread_pool_entry_struct * D;

#if FLINT_USES_PTHREAD
    pthread_mutex_lock(&T->mutex);
#endif

    D = T->tdata;
    if (T->length > 0)
    {
        for (i = 0; i < T->length; i++)
        {
            num += D[i].available;
        }
    }

#if FLINT_USES_PTHREAD
    pthread_mutex_unlock(&T->mutex);
#endif

    return num;
}

slong flint_get_num_available_threads()
{
    if (global_thread_pool_initialized)
        return thread_pool_num_available(global_thread_pool) + 1;

    return flint_get_num_threads();
}
```

The idea is that when selecting between algorithms, we sometimes want to make a choice depending on whether parallel computation is possible. For example, algorithm A might be strictly serial and 1.5x faster than algorithm B which is embarrassingly parallel, in which case we want to use algorithm B if there are >= 2 threads.

We typically do this by calling flint_get_num_threads(). However, this is not accurate if we are already inside parallel code and some workers are occupied.

I guess the intended solution is to call thread_pool_request() and check how many threads you get. But this is annoying when the thread handles are not needed immediately/explicitly, so I thought it'd make sense to have a function that just returns the count.

**Comment by tthsqe12** [comment]
Yeah, you can add this if you want a better ahead-of-time estimate on how many threads you are probably going to get.

**Comment by fredrik-johansson** [comment]
Is the mutex needed? It shouldn't matter much if another thread changes D[i].available (you just get the wrong count), but there would be an issue if another thread causes the thread pool to reallocate/resize its data. Can that happen?

**Comment by tthsqe12** [comment]
Without the mutex you can get inaccurate counts, or crashes if someone else resizes the thing. But, this second case shouldn't happen in practice.
