### ISSUE TITLE
Test failure in test-t-sdiv_qrnnd (back)

### ISSUE THREAD

**Issue by SnarkBoojum** [flintlib/flint2#1175]
This is a dupe from #1140, but since I didn't manage to re-open it, I guess it's worth opening a new one: 2.9.0 is supposed to fix this, but:

1. I got a [report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016296) claiming it's back.
2. I could reproduce it.
3. I have the same dmesg error.

**Comment by narc-Ontakac2** [comment]
For some reason the commit that is supposed to fix this is not in v2.9.0.

**Comment by txgk** [comment]
Which commit fixes this exactly? I face this problem on Alpine too and would like to patch the bug.

**Comment by narc-Ontakac2** [comment]
https://github.com/wbhart/flint2/commit/fb8ddbcc06afa2a8f25637032fbb8211f6c6c122

-- 
Papier ist gebundenes CO2. Bitte drucken Sie diese EMail aus und
archivieren Sie sie.

**Comment by txgk** [comment]
Thank you, that fixes the test.

**Comment by albinahlback** [comment]
I suppose this is fixed. Feel free to reopen if this is still an issue.
