### ISSUE TITLE
Move this to a dedicated GitHub organization?

### ISSUE THREAD

**Issue by fingolfin** [flintlib/flint2#1180]
With maintainership of flint2 moving from @wbhart to @fredrik-johansson I wonder if it wouldn't make sense to register a GitHub organization (such as https://github.com/flintlib/ -- flint sadly is taken) and then moving this repository (with all its issues and PRs) over there? This would automatically create redirects from the old URLs to the new ones (at least as long as @wbhart doesn't create a fresh clone).

The advantage would be that the whole project is less tied to a single person, one gains flexibility in how one assign access rights etc.

**Comment by edgarcosta** [comment]
This would also provide an obvious home for the NTL interface as a separate projective, see #1039.

**Comment by wbhart** [comment]
The repository will be transferred to Fredrik Johansson in the next days
*before* any decision is made about a community repository. That is solely
at Fredrik's discretion as he is maintainer. He will announce something on
the list if he decides that is what he wants to do.

Bill.

**Comment by fredrik-johansson** [comment]
Done!
