### ISSUE TITLE
Detach from fredrik-johansson/flint2

### ISSUE THREAD

**Issue by saraedum** [flintlib/flint2#1187]
Currently, this is shown as a fork of fredrik's repository. While this is apparently how the original repo was created at some point (and then moved,) I guess this is not true anymore since this is actually the upstream repository and fredrik's is just a fork?

![image](https://user-images.githubusercontent.com/373765/201429374-c3dbfbf4-f363-448b-bac0-305aa03690a4.png)

Should we request from GitHub to sever this tie? (They can apparently do this manually upon request.)

Apart from the looks, this also makes it impossible to code-search here. Code searches can only be done in the upstream repositories.

**Comment by fredrik-johansson** [comment]
Yes, that would be good if it's possible.

**Comment by fredrik-johansson** [comment]
Done. Everything looks fine?

**Comment by saraedum** [comment]
Great. Thank you!
