### ISSUE TITLE
Merge Arb, Calcium, generic-rings

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint2#1218]
At

https://github.com/fredrik-johansson/flint2/tree/alltogether/

is a branch of Flint with Arb, Calcium and generic-rings all merged into the same project (Antic was merged previously). This issue is to discuss going forward with such a mega-Flint, perhaps starting with a new major version number.

Rationale for merging Arb and Calcium back into Flint:

* If Flint C is a "library for doing number theory" then the exclusion of the number-theoretically important domains currently covered by Arb and Calcium (real/complex numbers, qqbar, transcendental number fields) is somewhat artificial.

* This will significantly reduce the shared maintenance burden for these projects. Also, downstream projects will have fewer dependencies and version conflicts to worry about.

* Arb and Calcium rely heavily on Flint internals. It has been awkward adding cutting-edge features to Flint and having to wait for these to be usable in Arb and Calcium. Indeed, there are many functions in Arb and Calcium that logically belong in Flint but were not placed in Flint because of this.

* It becomes possible to use Arb numerics in core Flint functions (fmpz, fmpq, etc.). I have already replaced a few thousand lines of obsolete Flint code with Arb wrappers in this branch (e.g. to compute Bernoulli numbers); more can be done.

Rationale for generic-rings (see https://fredrikj.net/generic-rings/):

* Flint/Arb/Calcium already have several ad-hoc generic systems, not to mention many tens of thousand lines of essentially duplicated or boilerplate code, most of which could be refactored to use the new generics. Notably, there is a lot of bloat duplicating the same implementations of algorithms and structures multiple times over arb/acb and nmod/fmpz_mod/fq/fq_nmod/fq_zech. For finite fields the template system keeps the source code manageable but compiling the same thing 3x adds bloat.

* It will be easy to add extra specialized ground types to improve performance, e.g. fixed-precision floating-point types and fixed-width finite field implementations (see nmod8 for a prototype).

* This makes it really eay to add new domains and extend existing ones. Note that generic-rings already implements:
  - proper vector types (gr_vec_t)
  - polynomials and matrices usable with any ground type
  - power series (very basic; absolute precision model only for now)
  - multivariate polynomials (incomplete; only some functions implemented)
The generics would also make it easy to add the frequently-requested sparse matrices, etc.

* It becomes easier to wrap Flint since the various types can be interfaced via the same generics interface. Indeed, there is now a Python wrapper part of the repository. This wrapper uses ctypes so it is quite slow, but it is very handy for testing things. It is getting close to the feature coverage of Nemo or python_flint with an order of magnitude less code.

* The generics interface also provides a uniform, memory-safe approach to error handling.

* Generic-rings deals more robustly than Sage, AbstractAlgebra etc. with inexact and noncomputable domains, by extending the principles of interval arithmetic to structures on top of inexact ground types; using triple-valued logic, etc.

How bad is the bloat? With ``./configure --disable-static``, current trunk builds in 62 seconds with ``make -j``. The merged repo builds in 99 seconds, so 60% worse. It should be possible to reduce this in the future by using generic-rings more extensively, optimizing header files and removing obsolete code.

Misc comments:

* Merging the documentation is a work-in-progress.

* I did have to make a change to the Makefile (avoiding a $(wildcard)) because the source file list exceeded the shell's 128kB command line limit.

* I have changed the default flint_test_multiplier to 1.0, arb_test_multiplier to 0.1 and calcium_test_multiplier to 0.1 to speed up running all the tests. Of course, one should test with bigger multipliers during development and before releases, but it's mostly a waste of time to run millions of iterations of each test all the time (it would be better to improve the test code!).

* I have made some other minor cleanup, including moving the flintxx headers to their own directory.

Builds pass except on MinGW GCC (which in any case was failing randomly; see #1206). Someone will have to investigate that.

I think FLINT_ASSERT builds also fail (IIRC Calcium triggers an assertion failure in fmpz_lll).

**Comment by oscarbenjamin** [comment]
> current trunk builds in 62 seconds with `make -j`. The merged repo builds in 99 seconds, so 60% worse.

Does this just compare building Flint vs building mega-Flint?

Presumably the build time for mega-Flint is less than the total time taken to build flint+Arb etc separately.

**Comment by fredrik-johansson** [comment]
Yes.

Arb takes 22 s, Calcium 10 s, generic-rings 5 s, so it's pretty much the sum of the build times.

**Comment by isuruf** [comment]
The way they are merged now will erase history from arb, calcium and generic-rings. It should not be hard to at least keep the histories for the new files being added. (By asking git to trim the history of arb to only that of the new files and then merging them together)

**Comment by fredrik-johansson** [comment]
> The way they are merged now will erase history from arb, calcium and generic-rings. It should not be hard to at least keep the histories for the new files being added. (By asking git to trim the history of arb to only that of the new files and then merging them together. I can try to do this if you prefer.)

That would be excellent!

**Comment by oscarbenjamin** [comment]
The human time required to figure out many libraries, packages, versions, combinations and configurations is much more than just finding one and getting it configured and built so there is a definite benefit there.

There are significant *potential* downsides here though. If the end result is something that is cleaner and easier for you to maintain right now then that is good. I hope it also becomes something that is easier for others to maintain in future though. The more stuff there is in a project the harder it becomes to maintain because anyone who volunteers to do so takes on responsibility for more including some parts that they are less interested in and/or that are in poorer condition. On the other hand if the total of what needs to be maintained gets easier to maintain as well as more useful (and more used) then maybe that means that more people will volunteer to team together and keep it going.

From my perspective mega-Flint is very convenient but I expect this to be almost an irreversible change so let's hope it works out for the best in the long term!

**Comment by Joel-Dahne** [comment]
I think all the reasons you mention for merging are good. In particular the reduced maintenance burden is a very important part. I have a few comments:

For the work I do I don't think this change would have any negative effects. I tried building [FLINT_jll](https://github.com/JuliaBinaryWrappers/FLINT_jll.jl) using this branch and update [Arblib.jl](https://github.com/kalmarek/Arblib.jl) to depend only on `FLINT_jll`. That seemed to work perfectly fine, after taking into account the ABI change to `arb_poly_struct` and `acb_poly_struct`.

I think @isuruf  point about keeping the git history is very important. It is fairly common that I look through the history or use `git-blame` to try and understand a piece of code, I have done this several times for Arb.

I think how the documentation is merged is also an important aspect. At the moment the Arb documentation is more or less self contained, making it easier for new people. If they are put together into one mega-documentation I feel like it might be a bit too much information to handle for new people. On the other hand you sometimes have to jump between the documentations at the moment, avoiding that might make it easier in some cases.

**Comment by fredrik-johansson** [comment]
Excellent feedback, thanks.

The Arb modules will more or less end up together like one chapter in the Flint documentation, with their own introductory text, but I think it should be relatively easy to also maintain a self-contained version of the Arb documentation at https://arblib.org/

**Comment by Joel-Dahne** [comment]
I think this change would also make it easier for people that are already using Flint or Arb to also start using functionality from Calcium and generic-rings. 

At least that would be the case for me. In general I hesitating to pull in more dependencies than necessary so I would avoid starting to depend on Calcium and generic-rings if I don't really need them. If they came with Flint it would be much more likely that I would use them.

**Comment by fredrik-johansson** [comment]
Yes, that is an important point.

@isuruf Want to try a history-preserving merge?

I have already done a fair bit of development in this branch after the initial merge, so it would be good to get things into trunk before any major divergence occurs

**Comment by isuruf** [comment]
@fredrik-johansson, have a look at https://github.com/isuruf/flint2/tree/alltogether
I only did arb for now. Let me know if it looks okay. If so, I can do calcium and gr too.
Here's the script that I used (flint2 and arb were in the same directory with the remote `upstream` being set to flintlib and remote `fredrik` set to your fork)
```bash
cd flint2
git reset --hard upstream/trunk
git ls-files > ../arb/flint2.txt
git reset --hard fredrik/alltogether
cd ../arb
git checkout master
git reset --hard upstream/master
for f in $(cat $flint2.txt); do
  if [[ -f "$f" ]]; then
    rm $f;
    git add $f;
  fi
done
git commit -m "Delete files that are in common with flint2"
for f in $(git ls-files); do
  if [[ ! -f "../flint2/$f" ]]; then
    rm $f;
    git add $f;
  fi
done
git commit -m "Delete files that were not merged"
cd ../flint2
git reset --hard upstream/trunk
git remote add arb $PWD/../arb
git fetch arb master
git merge arb/master --allow-unrelated-histories -m "Merge all of arb into flint2"
git branch merged-arb
git checkout master
git reset --hard fredrik/alltogether
git rebase merged-arb -X ours
```

With the script the monster commit https://github.com/fredrik-johansson/flint2/commit/9fcb705865a63fdf2a0b6880add28d6422803cd0 simply became https://github.com/isuruf/flint2/commit/64ba5856ab428b7cefb4bcbcfe08bc5890401ce9

**Comment by fredrik-johansson** [comment]
@isuruf Wow, that's great! Yes, if you can do Calcium and GR too, please go ahead! Then just open a PR.

**Comment by fredrik-johansson** [comment]
It's done! Huge thanks @isuruf. I will open separate issues for remaining integration work to be done.
