### ISSUE TITLE
Separate CFLAGS for tests

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint2#1234]
Currently we compile test programs with ``-O2 -funroll-loops`` by default but I think we could just use ``-O1`` or even ``-O0``. There's nothing worth optimizing in most test programs except the build time.

**Comment by fredrik-johansson** [comment]
Time for ``make -j check`` once the library has been built:

Default (``-O2 -funroll-loops``):

    real	3m3,100s
    user	25m24,479s
    sys	2m42,080s

With ``-O1``:

    real	2m59,047s
    user	24m23,809s
    sys	2m42,069s


With ``-O0``:

    real	2m52,763s
    user	23m6,007s
    sys	2m35,555s

**Comment by albinahlback** [comment]
This is completed. One can use TESTCLAGS.
