### ISSUE TITLE
Remove `FLINT_NO_WORDMAC`

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1242]
Currently, `flint.h` contains lines saying
```
#ifndef FLINT_NO_WORDMAC
#define UWORD_MAX ULLONG_MAX
#define UWORD_MIN ULLONG_MIN
#define WORD_MAX LLONG_MAX
#define WORD_MIN LLONG_MIN
#endif
```
However, there is no reference to `FLINT_NO_WORDMAC` anywhere. I suppose this is a residue from years ago. Should this be removed?

**Comment by fredrik-johansson** [comment]
Explained in #490.
