### ISSUE TITLE
Only do subset of tests for slow jobs on PR

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1243]
For slow jobs (FreeBSD, MinGW and Cygwin), I was thinking if we can do only a subset of the tests for PRs in order to speed up these jobs. Then we can still perform extensive tests when PRs are merged (see [this SO-post](https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged)).

One could attack this from two aspects:
1. Don't double test things. For example, `fmpz_add` is used pretty much everywhere, so perhaps running the specific test for `fmpz_add` is not really necessary for these slow jobs.
2. Don't test things that are not used as much. Perhaps stuff like `fq_default_mat`, `fmpz_poly_mat` and `fq_zech_mpoly_factor` has to be tested.

If this is a good idea, what is necessary to test?

Also take into consideration that with the new makefile we can test individual tests; testing any test file `$(SRC_DIR)/my_dir/test/t-mytest.c` only requires us to run `make $(BUILD_DIR)/my_dir/test/t-mytest_RUN`, and it will build everything that is necessary, and then run it.

**Comment by albinahlback** [comment]
I think this list of directories is a good outline (you can compare them to `DIRS` in `Makefile.in`):
```
        thread_pool                     thread_support

        ulong_extras

        mpn_extras
        nmod            nmod_vec        nmod_mat        nmod_poly
        fmpz            fmpz_vec        fmpz_mat        fmpz_poly
        fmpz_mod        fmpz_mod_vec    fmpz_mod_mat    fmpz_mod_poly
        fmpq            fmpq_vec        fmpq_mat        fmpq_poly

        fq                                              fq_poly
                        fq_nmod_vec
                                        fq_zech_mat
        fq_nmod_embed
        padic
        qadic

        nmod_poly_factor                fmpz_factor

        mpoly                           fmpz_mpoly
                        fq_nmod_mpoly

        nmod_mpoly_factor

        fft                             fmpz_lll
        arith           qsieve          aprcl

        nf              nf_elem         qfb

                        fmpzi
                                        arb             acb
        arb_mat         arb_poly
        acb_mat         acb_poly        acb_calc        acb_hypgeom
        arb_fmpz_poly
        acb_dft         acb_elliptic    acb_modular     acb_dirichlet
        dirichlet       bernoulli       hypgeom

        gr              gr_vec          gr_mat          gr_poly
        gr_mpoly        gr_special

        calcium
        utils_flint     fmpz_mpoly_q
        fexpr           fexpr_builtin
        qqbar
        ca              ca_ext          ca_field        ca_vec
        ca_poly         ca_mat
```
This list contains 76 directories, compared to the original 131.

**Comment by fredrik-johansson** [comment]
I'm not really a fan of this. I'd rather just set a lower default test multiplier for the slow systems, and work on making the whole test suite faster to compile.

**Comment by albinahlback** [comment]
Alright.
