### ISSUE TITLE
Automize the compilation and uploading of the documentation to website

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1259]
@fredrik-johansson How is FLINT hosted? Do you have your own server, or is it hosted somewhere else? Perhaps one should be able to write a script that can fetch the repository and check if there is any differences to the documentation. If so, it can just compile and upload the new documentation.

I know that one can upload private keys and so on to Github, but I would personally not trust that.

**Comment by fredrik-johansson** [comment]
It's hosted on my personal account on Opalstack along with a couple of other websites. Currently I just run a script locally on my computer when I want to upload a new revision of the documentation. I agree it would be nice to set up a bot to have the documentation track the git trunk.

**Comment by albinahlback** [comment]
This has been done.
