### ISSUE TITLE
`calcium_stream_init_str` hardcodes allocation size of `s`

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1285]
Now, I do not know of the internals of `calcium_stream`, but looks like it assumes that `sizeof(char)` equals to 1. If this is the case, it would be nice to get rid of.

**Comment by fredrik-johansson** [comment]
Are there any systems where ``sizeof(char)`` is not equal to 1?

**Comment by albinahlback** [comment]
I don't think so, but there may come a point in the future. Anyway, for the reader it is nice to have some sort of unit in mind, such as `number of char * bytes per char = bytes`.

Not important though. Feel free to close.
