### ISSUE TITLE
Endless warnings

### ISSUE THREAD

**Issue by thofma** [flintlib/flint2#1292]
I am getting an endless stream of warnings which are all of the form
```
  CC  fmpz_mpoly_factor/gcd_hensel.lo
clang: warning: argument unused during compilation: '-mpopcnt' [-Wunused-command-line-argument]
```
This happens for all files. Is this normal?

**Comment by albinahlback** [comment]
What compiler are you using? I do not get such warnings with GCC 12.2.1 with `-Wall`.

**Comment by thofma** [comment]
I can give you more information if you tell me what you need.

**Comment by albinahlback** [comment]
What is CFLAGS and CPPFLAGS?

**Comment by albinahlback** [comment]
Alright, let me check what I can do to solve this (perhaps I'll just set `-Wnounused-command-line-argument`)

**Comment by albinahlback** [comment]
Haha, I see what you mean.

**Comment by thofma** [comment]
`Target: arm64-apple-darwin22.3.0`

**Comment by albinahlback** [comment]
Alright. I know how to implement this. Will also silence a couple of other warnings. Give me an hour or so.

**Comment by thofma** [comment]
Thanks (its not that urgent).

**Comment by fredrik-johansson** [comment]
Unrelated to the issue of silencing unwanted warnings, but I wonder why we even bother to check for ``popcnt``. As far as I can tell, it's used in exactly one function and that function is maybe the least used function in FLINT. We may as well call ``mpn_popcnt`` with a single limb as input.

**Comment by albinahlback** [comment]
I believe Dan wanted it somewhere. I want to remove it as it may break compatibility between processors.

**Comment by albinahlback** [comment]
This should now be solved as the CFLAG `-mpopcnt` was removed from the default flags.

**Comment by thofma** [comment]
Yes, everything looks fine now, thanks!
