### ISSUE TITLE
Switch `count_[leading/trailing]_zeros` to builtins

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint2#1294]
FLINT already assumes that `__builtin_clz` is available in `longlong.h`. I think the compiler can better optimize the code with builtins rather than inline assembly. Moreover, it would be nice to write it like `count = count_leading_zeros(x)` instead of `count_leading_zeros(count, x)`.

Perhaps a rename would be fitting to avoid silent breakage. I think `flint_c[l/t]z` is very fitting.

We can test whether these functions are available during the configuration.

**Comment by fredrik-johansson** [comment]
Sure.

**Comment by thofma** [comment]
> We can test whether these functions are available during the configuration.

Is this a check for the `HOST` or `BUILD` during configuration?

**Comment by albinahlback** [comment]
Completed.
