### ISSUE TITLE
qsieve segfault in unwritable directory

### ISSUE THREAD

**Issue by orlitzky** [flintlib/flint2#1329]
If you run a program that uses `qsieve_factor()` in an unwritable directory, it will segfault trying to dump its relations to file:

```C
/* qsieve/factor.c */
nchars = sprintf(qs_inf->fname, "%d", (int) rand());
strcat(qs_inf->fname + nchars, "siqs.dat");
qs_inf->siqs = fopen(qs_inf->fname, "w");

/* qsieve/large_prime_variant.c */
flint_fprintf(qs_inf->siqs, "%X ", prime); /* write large prime */
```

First, I think it would be nice to handle the error now while it's easily reproducible. But I also think this should be using `mkstemp()` instead of a file in the current working directory. While `mkstemp()` can still fail in weird cases, it should generally just work, and has been a POSIX standard since 2001. I bet even Microsoft have gotten around to implementing it by now.

**Comment by albinahlback** [comment]
Yes, so this has been fixed. We assume that `TMPPATH=/tmp` when you run `./configure`, but you can set it via `./configure TMPPATH=/path/to/my/temporary/directory`.

**Comment by orlitzky** [comment]
Not just fixed, but fixed two months before I reported it :)

Sorry, I hadn't looked at the current git branch. I'm sure it will work for me, because it's exactly what I had in mind.

My only comment is that your configure-time `TMPPATH` might use the POSIX `TMPDIR` environment variable instead. Many other programs already allow you to override `/tmp` by setting `TMPDIR=/whatever` at runtime. It's not a problem for me personally however.

Thanks!

**Comment by albinahlback** [comment]
Oh, thanks for letting me know! I will change this name.
