### ISSUE TITLE
Change in behaviour when composing non-finite polynomials

### ISSUE THREAD

**Issue by Joel-Dahne** [flintlib/flint2#1372]
The change to using the `gr_poly` methods for composition of polynomials changed the previous behavior for polynomials for which some, but not all, of the terms are non-finite. More precisely, for `arb_poly_compose_series` the lines
```C
    else if (!_arb_vec_is_finite(poly1, len1) || !_arb_vec_is_finite(poly2, len2))
    {
        _arb_vec_indeterminate(res, n);
    }
```
means that if any of the coefficients are non-finite then all of the coefficients in the output are indeterminate. The previous behavior was that if some of the higher order coefficients were non-finite then the lower order coefficients would still be finite. 

I have made heavy use of the previous behavior when computing Taylor series of functions which are not everywhere differentiable. In that case evaluation on a ball containing a non-differentiable point would give a finite result for the constant coefficient but a non-finite result for the next coefficient. This has been convenient because it allows for using higher order enclosures when the function is differentiable and fall back to direct enclosures when it is not differentiable. With the new behavior non-finite enclosures for the derivatives gives non-finite enclosures also for the constant coefficient.

I believe the easiest way to give the old behavior would be to in the above branch compute the index for the first non-finite coefficient and then compute the composition only up to that coefficient and set all the remaining coefficient to indeterminate values.

The story is similar for `acb_compose_series`, `arb_compose` and `acb_compose`.

**Comment by fredrik-johansson** [comment]
I agree. Would you like to work on a patch?

**Comment by Joel-Dahne** [comment]
Yes, I can take care of it!
