### ISSUE TITLE
Support ICC

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint2#26]
See title.

**Comment by wbhart** [comment]
In particular, we should set the correct floating point flags for ICC and MSVC.

**Comment by albinahlback** [comment]
Is ICC not supported? What happens if you compile with ICC? I don't know how to download it.

**Comment by fredrik-johansson** [comment]
I don't know if anyone cares about this anymore. If they do and ICC is currently broken, I suppose they can open a new issue.
